Repository Out-of-Type-O/Today_Workout_Done, pull requests merged in 2024-12, with the labels that each got.

#10 Feat #8: userlist-modal
  src/assets/defaultUser.png
  src/assets/searchIcon.svg
  src/components/userlistModal/UserBox.tsx
  src/components/userlistModal/UserListModal.tsx
  src/css/tailwind.css
Labels: ✨ feat

#15 style: layout, header 수정
  src/components/rootlayout/Header.tsx
  src/layouts/RootLayout.tsx
Labels: 🎨 Design

#17 [FEAT] : 사이드바 퍼블리싱 완료
  src/assets/dumbbell_icon.svg
  src/assets/gym_icon.svg
  src/assets/profile-edit.svg
  src/assets/protein_icon.svg
  src/assets/routine_icon.svg
  src/components/ChannelList.tsx
  src/components/rootlayout/Header.tsx
  src/components/rootlayout/Sidebar.tsx
  src/css/index.css
  tailwind.config.js
Labels: ✨ Feat

#19 [Fix] 유저목록 모달창 수정 #18
  src/assets/close.svg
  src/components/rootlayout/Sidebar.tsx
  src/components/userlistModal/UserListModal.tsx
  src/css/tailwind.css
Labels: 🔧 Fix

#20 [FEAT] 로그인 / 회원가입 UI 구현 / 헤더 수정
  src/App.tsx
  src/assets/authImg.svg
  src/components/rootlayout/Header.tsx
  src/layouts/AuthLayout.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: ✨ Feat

#23 [FEAT] userProfile 컴포넌트화
  src/components/UserProfile.tsx
  src/components/rootlayout/Header.tsx
  src/components/rootlayout/Sidebar.tsx
  src/types/UserProfile.d.ts
Labels: ✨ Feat

#26 Fix header알림아이콘 추가 #25
  src/assets/notifyIcon.svg
  src/components/ChannelList.tsx
  src/components/rootlayout/Header.tsx
  src/components/rootlayout/Sidebar.tsx
Labels: 🔧 Fix

#29 [FIX] login ui 수정
  src/css/index.css
  src/layouts/AuthLayout.tsx
Labels: 🎨 Design

#31 [FEAT] feed 페이지 퍼블리싱(썸네일카드, 검색창, 태그)
  src/assets/chat_icon.svg
  src/assets/images/feed_thumbnail.jpg
  src/assets/like_icon.svg
  src/components/ChannelList.tsx
  src/components/ImageCard.tsx
  src/components/SearchBar.tsx
  src/components/Tag.tsx
  src/components/rootlayout/Sidebar.tsx
  src/layouts/RootLayout.tsx
  src/pages/Home.tsx
Labels: ✨ Feat

#30 feat: loginform ui 완료
  src/components/LoginForm.tsx
Labels: ✨ Feat

#33 feat: 회원가입
  package.json
  src/layouts/AuthLayout.tsx
  src/pages/Signup.tsx
Labels: ✨ Feat

#36 [FIX] signup page error 수정
  src/pages/Signup.tsx
Labels: 🔧 Fix

#39 [feat] 유저목록 모달창 에러 퍼블리싱
  src/components/ChannelList.tsx
  src/components/userlistModal/UserListModal.tsx
  src/components/userlistModal/UserNone.tsx
Labels: ✨ Feat

#41 [Design]회원가입 사이즈변경 #40
  src/assets/cycle.svg
  src/components/rootlayout/Header.tsx
  src/css/index.css
  src/layouts/AuthLayout.tsx
  src/pages/Signup.tsx
  src/styles/fonts.css
  tailwind.config.js
Labels: 🎨 Design

#50 [FEAT] user page #21
  src/App.tsx
  src/components/FollowButton.tsx
  src/components/User/UserCard.tsx
  src/pages/User.tsx
Labels: ✨ Feat

#53 [FEAT] 유저목록 모달창 검색기능 구현 #48
  src/components/rootlayout/Sidebar.tsx
  src/components/userlistModal/UserListModal.tsx
  src/utils/searchUser.ts
Labels: ✨ Feat

#55 [feat] 유저목록 프로필사진 구현완료_#54
  src/components/userlistModal/UserBox.tsx
  src/components/userlistModal/UserListModal.tsx
  src/utils/getUserList.ts
  src/utils/searchUser.ts
Labels: ✨ Feat

#58 [FEAT] 사이드바 토글, 활성화
  src/assets/user_icon.svg
  src/components/ChannelList.tsx
  src/components/rootlayout/Sidebar.tsx
  src/pages/Home.tsx
Labels: ✨ Feat

#60 [Refactor]57_Make_ButtonComponents
  src/components/ButtonComponent.tsx
  src/components/rootlayout/Header.tsx
Labels: 🔨 Refactor

#62 Fix 회원가입 버그수정 #49
  src/pages/Signup.tsx
Labels: 🔧 Fix

#64 [Design]#63_sitename&Favicon
  index.html
  src/assets/images/Favicon.png
Labels: 🎨 Design

#66 [FEAT] 사이드바 토글 전역상태관리
  src/components/rootlayout/Sidebar.tsx
  src/layouts/RootLayout.tsx
  src/stores/sideberToggleStore.ts
Labels: ✨ Feat

#65 [FEAT] login 기능 구현
  src/api/axios.ts
  src/pages/Login.tsx
  src/stores/authStore.ts
  src/types/UserInfo.d.ts
Labels: ✨ Feat

#71 [FIX] : 타입 에러 수정
  src/stores/authStore.ts
  src/types/UserInfo.d.ts
Labels: 🔧 Fix

#76 [FEAT] : private 라우터 구현
  src/App.tsx
  src/route/PrivateRoute.tsx
  src/route/PublicRoute.tsx
Labels: ✨ Feat

#72 [FEAT]#67_isloggedin_Header
  src/components/ButtonComponent.tsx
  src/components/UserProfile.tsx
  src/components/rootlayout/Header.tsx
  src/types/ButtonComponent.d.ts
  src/types/UserProfile.d.ts
Labels: ✨ Feat

#80 [FEAT]#79_logoOnOffbySidebar_newPostButton
  src/components/rootlayout/Header.tsx
  src/layouts/RootLayout.tsx
Labels: ✨ Feat, 🎨 Design

#81 [FEAT] 새로고침시 로그인 정보와 유저 정보 보관하기
  src/pages/Login.tsx
  src/stores/authStore.ts
Labels: ✨ Feat

#83 [feat]82_header_logout
  src/components/rootlayout/Header.tsx
Labels: ✨ Feat

#85 [DESIGN] 피드 카드 크기 수정
  src/components/ChannelList.tsx
  src/components/ImageCard.tsx
  src/components/rootlayout/Sidebar.tsx
Labels: 🎨 Design

#86 Feat 게시글 작성페이지 퍼블리싱 완료 #69
  src/assets/down.svg
  src/assets/selectChannel.svg
  src/assets/uploadImgIcon.svg
  src/assets/writeTitle.svg
  src/components/rootlayout/Sidebar.tsx
  src/components/userlistModal/UserListModal.tsx
  src/css/tailwind.css
  src/pages/Posting.tsx
Labels: ✨ Feat

#91 Feat 비밀번호 제한 #87
  src/assets/private.svg
  src/assets/showpw.svg
  src/pages/Signup.tsx
Labels: ✨ Feat, 🔧 Fix

#92 [FIX]: 토큰 값 수정
  src/pages/Login.tsx
Labels: 🔧 Fix

#90 [Feat]게시글등록-api요청 #88
  src/components/posting/PostStatus.tsx
  src/pages/Posting.tsx
  src/utils/postingFn.ts
Labels: ✨ Feat

#94 [FEAT] 게시글 보기 페이지 퍼블리싱 #73
  src/App.tsx
  src/assets/chat_icon_black.svg
  src/assets/trash.svg
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/CommentForm.tsx
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
Labels: 🎨 Design

#97 [fix] 이미지 업로드 수정완료
  src/components/rootlayout/Header.tsx
  src/pages/Posting.tsx
  src/utils/postingFn.ts
Labels: 🔧 Fix

#105 [FEAT] 모달창 상세유저페이지 연결, 사이드바 색상 수정
  src/components/ChannelList.tsx
  src/components/rootlayout/Sidebar.tsx
  src/components/userlistModal/UserBox.tsx
  src/components/userlistModal/UserListModal.tsx
Labels: ✨ Feat

#104 102 featheader notification alarm
  src/components/rootlayout/Header.tsx
Labels: ✨ Feat

#109 fix: 사이드바 목록 간격 수정
  src/components/rootlayout/Sidebar.tsx
Labels: 🔧 Fix

#108 [FEAT] : 상세페이지 일부 구현
  src/api/axios.ts
  src/components/PostDetail/CommentForm.tsx
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
  src/types/Comment.d.ts
  src/types/Like.d.ts
Labels: ✨ Feat

#110 [FEAT] 게시물작성페이지 분기처리
  src/App.tsx
Labels: ✨ Feat

#115 [FIX] 유저모달창 팔로잉버튼 로그인 분기처리
  src/components/userlistModal/UserBox.tsx
Labels: 🔧 Fix

#117 [FIX] 카드 크기 resize
  src/components/ImageCard.tsx
Labels: 🎨 Design

#123 feat: 위로가기 버튼
  src/assets/scrollUp.svg
  src/pages/Home.tsx
Labels: ✨ Feat

#122 Feat 오운완채널 #56
  src/App.tsx
  src/components/ImageCard.tsx
  src/pages/Home.tsx
Labels: 🔧 Fix

#129 [FEAT] 게시판 수정 구현중
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
  src/utils/updatePost.ts
Labels: ✨ Feat

#127 [FEAT]Header_Alarm_Form_first
  src/components/rootlayout/Header.tsx
Labels: ✨ Feat, 🎨 Design

#132 124 feat 게시글 삭제 확인 모달
  src/components/button/ModeChange.tsx
  src/components/modal/DeleteConfirm.tsx
Labels: ✨ Feat

#131 [FEAT] 마이페이지 이름 수정 구현
  src/App.tsx
  src/components/User/UserCard.tsx
  src/components/UserProfile.tsx
  src/pages/MyPage.tsx
  src/pages/User.tsx
  src/stores/authStore.ts
  src/types/UserInfo.d.ts
  src/types/UserProfile.d.ts
  src/utils/updateName.ts
Labels: ✨ Feat

#135 Feat 유저프로필이미지 변경 #133
  src/components/User/UserCard.tsx
  src/components/UserProfile.tsx
  src/pages/MyPage.tsx
  src/types/UserProfile.d.ts
  src/utils/updateUserImg.ts
Labels: ✨ Feat

#138 [FEAT] 게시물 수정 구현
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
Labels: ✨ Feat

#141 [FEAT] 이미지 카드 라우터 설정
  src/App.tsx
  src/components/ImageCard.tsx
  src/pages/Home.tsx
  src/pages/PostDetail.tsx
Labels: ✨ Feat

#142 [FEAT] 댓글 기능 구현
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/CommentForm.tsx
  src/components/PostDetail/CommentSec.tsx
  src/pages/PostDetail.tsx
  src/utils/commentFn.ts
  src/utils/getPostDetail.ts
Labels: ✨ Feat

#147 [FIX] 댓글 기능 #146
  src/components/PostDetail/CommentForm.tsx
  src/components/PostDetail/CommentSec.tsx
  src/pages/PostDetail.tsx
  src/utils/commentFn.ts
Labels: 🔧 Fix

#143 [feat]notification_form_1st
  src/assets/noti_follow_Icon.svg
  src/assets/noti_like_Icon.svg
  src/assets/noti_message_icon.svg
  src/components/NotificationBox.tsx
  src/components/notification/Notification.tsx
  src/components/rootlayout/Header.tsx
Labels: ✨ Feat, 🔨 Refactor, 🎨 Design

#144 Feat: 리뷰 게시판 퍼블리싱 #128
  src/App.tsx
  src/components/ChannelList.tsx
  src/components/ImageCard.tsx
  src/components/Review.tsx
  src/pages/ReviewPost.tsx
  tailwind.config.js
Labels: ✨ Feat

#152 Fix 게시글등록 후처리 #149
  src/pages/MyPage.tsx
  src/pages/Posting.tsx
  src/types/Post.d.ts
Labels: 🔧 Fix

#151 [FEAT] 로그인 상태관리 수정 및 사이드바 유저 정보 연결
  src/App.tsx
  src/api/axios.ts
  src/components/rootlayout/Header.tsx
  src/components/rootlayout/Sidebar.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/stores/authStore.ts
  src/stores/toeknStore.ts
  src/utils/verifyUser.ts
Labels: ✨ Feat

#155 [FIX] 게시글 프로필사진 적용
  src/components/ImageCard.tsx
  src/types/Post.d.ts
Labels: 🔧 Fix

#157 fix: 다크모드버튼 호버
  src/components/button/ModeChange.tsx
Labels: 🔧 Fix

#161 Fix 다크모드버튼 위치변경 #158
  src/assets/horizontalAfternoon.svg
  src/assets/innercircle.svg
  src/components/button/ModeChange.tsx
  src/components/rootlayout/Header.tsx
  src/components/rootlayout/Sidebar.tsx
  src/layouts/RootLayout.tsx
  src/pages/Home.tsx
Labels: 🔧 Fix

#163 [FEAT] 게시물 삭제 구현
  src/components/PostDetail/PostInfo.tsx
  src/components/modal/DeleteConfirm.tsx
  src/pages/PostDetail.tsx
  src/utils/api/deletePosts.ts
Labels: ✨ Feat

#164 [FIX] 프사 변경 시 실시간 적용 X, 새로고침 진행
  src/components/UserProfile.tsx
  src/pages/MyPage.tsx
Labels: 🔧 Fix

#167 FIX 사이드바 프사적용, 마이페이지 사이즈 변경
  src/components/rootlayout/Sidebar.tsx
  src/pages/MyPage.tsx
  src/stores/authStore.ts
Labels: 🔧 Fix

#168 [FEAT] 좋아요 기능 추가
  src/assets/icons/like_fill_icon.svg
  src/assets/like_icon.svg
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/CommentForm.tsx
  src/components/PostDetail/CommentSec.tsx
  src/components/Review.tsx
  src/pages/PostDetail.tsx
  src/stores/authStore.ts
  src/utils/postLikeFn.ts
Labels: ✨ Feat

#169 Fix 게시물 렌더링 #153
  src/components/ChannelList.tsx
  src/components/ImageCard.tsx
  src/components/LoginForm.tsx
  src/components/Review.tsx
  src/components/rootlayout/Sidebar.tsx
  src/pages/Home.tsx
  src/pages/ReviewPost.tsx
Labels: ✨ Feat

#174 [FIX] 좋아요 추가 삭제 기능 로직 변경
  src/components/PostDetail/CommentForm.tsx
  src/components/PostDetail/CommentSec.tsx
  src/utils/postLikeFn.ts
Labels: ✨ Feat

#175 [FEAT] 인증횟수 표시 및 원그래프로 표현
  package.json
  src/components/checkDone/CheckDone.tsx
  src/components/checkDone/CheckDoneMonth.tsx
  src/components/checkDone/DoneProgressBar.tsx
  src/components/rootlayout/Sidebar.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feat

#177 [BUG] 로그인 버그 해결
  src/components/checkDone/CheckDone.tsx
  src/components/rootlayout/Header.tsx
  src/pages/PostDetail.tsx
  src/stores/authStore.ts
  src/stores/toeknStore.ts
Labels: 🐛 Bug

#178 [FEAT] 로딩창 추가
  package.json
  src/assets/lottie/loading-b.json
  src/assets/lottie/loading.json
  src/components/Loading.tsx
  src/layouts/RootLayout.tsx
  src/pages/Home.tsx
  src/stores/loadingStore.ts
Labels: ✨ Feat

#181 [FIX] 게시글 등록 폼 수정
  src/components/posting/PostStatus.tsx
  src/components/rootlayout/Sidebar.tsx
  src/pages/Posting.tsx
Labels: 🔧 Fix

#184 [DESIGN] 사이드바 마이페이지 연결 유저모달 UI 수정 #183
  src/assets/icons/home_icon.svg
  src/components/FollowButton.tsx
  src/components/UserProfile.tsx
  src/components/rootlayout/Sidebar.tsx
  src/components/userlistModal/UserBox.tsx
  src/types/UserProfile.d.ts
Labels: ✨ Feat, 🎨 Design

#186 [FEAT] 달력 구현완료
  package.json
  src/components/MyPage/CustomCalendar.tsx
  src/constants/channel.ts
  src/css/calendar.css
  src/css/index.css
  src/pages/MyPage.tsx
Labels: ✨ Feat

#187 FEAT 게시글 작성, 유저정보 수정 시 로딩창 추가
  src/components/User/UserCard.tsx
  src/components/UserProfile.tsx
  src/pages/MyPage.tsx
  src/pages/Posting.tsx
Labels: ✨ Feat

#190 [DESIGN] 마이페이지 디자인 수정
  index.html
  src/components/User/UserCard.tsx
  src/components/checkDone/CheckDone.tsx
  src/components/checkDone/CheckDoneMonth.tsx
  src/components/checkDone/DoneProgressBar.tsx
  src/css/calendar.css
  src/pages/MyPage.tsx
Labels: 🎨 Design

#191 [FEAT] 이미지 hover 추가 및 최소 사이즈 지정
  src/components/PostDetail/PostInfo.tsx
Labels: ✨ Feat

#194 [FEAT] 삭제 모달시 스크롤 제한
  src/components/PostDetail/PostInfo.tsx
Labels: ✨ Feat

#195 [FIX] 운동 횟수 중복 제거
  src/components/checkDone/CheckDone.tsx
Labels: 🔧 Fix

#198 [FIX] 게시물 내용 수정창 수정
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
Labels: 🐛 Bug, 🔧 Fix

#199 [FEAT] 게시판상단 채널명 표시
  src/App.tsx
  src/components/ImageCard.tsx
  src/components/PostDetail/PostInfo.tsx
  src/components/Review.tsx
  src/constants/channel.ts
Labels: ✨ Feat, 🔧 Fix

#201 [DESIGN] 스타일 일부 수정
  src/assets/defaultUser.svg
  src/components/ChannelList.tsx
  src/components/ImageCard.tsx
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/PostInfo.tsx
  src/components/Review.tsx
  src/components/User/UserCard.tsx
  src/components/UserProfile.tsx
  src/components/button/ModeChange.tsx
  src/components/checkDone/CheckDoneMonth.tsx
  src/components/rootlayout/Header.tsx
  src/components/rootlayout/Sidebar.tsx
  src/components/userlistModal/UserBox.tsx
  src/css/fonts.css
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/types/UserProfile.d.ts
  tailwind.config.js
Labels: 🎨 Design

#205 [FIX] 상세게시글 유저 프로필사진 수정
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
Labels: 🔧 Fix

#208 [FEAT] 이전/다음 페이지 이동 #166
  src/assets/icons/double-left_blue.svg
  src/assets/icons/double-right_blue.svg
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
Labels: ✨ Feat, 🔧 Fix

#207 [FIX] 이미지 카드 호버시 본인이 좋아요한 것은 하트 활성화
  src/components/ImageCard.tsx
  src/types/Post.d.ts
Labels: 🔧 Fix

#210 [FIX] : private / public route 수정
  src/App.tsx
  src/route/PrivateRoute.tsx
  src/route/PublicRoute.tsx
  src/stores/authStore.ts
  src/utils/verifyUser.ts
Labels: 🔧 Fix

#212 [FEAT] 팔로우 언팔로우
  src/components/FollowButton.tsx
  src/components/userlistModal/UserBox.tsx
  src/stores/authStore.ts
  src/utils/followFn.ts
Labels: ✨ Feat

#217 [FIX] 댓글박스 유저 프로필 사진 추가
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/CommentForm.tsx
  src/pages/PostDetail.tsx
  src/utils/getPostDetail.ts
Labels: 🔧 Fix

#220 fix: 닉네임 제한 조건 수정 및 버그 해결
  src/pages/Signup.tsx
Labels: 🐛 Bug, 🔧 Fix

#222 style: 전역 폰트 다운 적용
  src/assets/fonts/Pretendard-Black.woff
  src/assets/fonts/Pretendard-Black.woff2
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard-ExtraLight.woff
  src/assets/fonts/Pretendard-ExtraLight.woff2
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Light.woff2
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/Pretendard-Thin.woff
  src/assets/fonts/Pretendard-Thin.woff2
  src/css/fonts.css
Labels: 🎨 Design

#223 [FEAT] 상세페이지 로딩화면 추가
  src/pages/PostDetail.tsx
Labels: ✨ Feat

#224 fix: 페이지이동 라우트 수정정
  src/pages/PostDetail.tsx
Labels: 🔧 Fix

#225 Bug 유저 목록창 팔로잉버튼 오류수정
  src/components/FollowButton.tsx
  src/components/User/UserCard.tsx
  src/components/userlistModal/UserBox.tsx
  src/pages/MyPage.tsx
  src/stores/authStore.ts
Labels: 🐛 Bug, 🔧 Fix

#228 [FIX] 포트번호 이동
  src/api/axios.ts
  src/constants/channel.ts
  src/pages/Home.tsx
  src/pages/Posting.tsx
  src/pages/ReviewPost.tsx
  src/stores/channelStore.ts
Labels: 🔧 Fix

#231 [FIX] 이미지카드 호버 버그 수정
  src/components/ImageCard.tsx
  src/pages/MyPage.tsx
Labels: 🔧 Fix

#236 [FEAT]202_comment/follow_NotificationCreate
  src/assets/icons/Comment_Icon.svg
  src/components/NotificationBox.tsx
  src/components/PostDetail/CommentSec.tsx
  src/components/notification/Notification.tsx
  src/components/rootlayout/Header.tsx
  src/pages/PostDetail.tsx
  src/utils/api/createNotification.ts
  src/utils/commentFn.ts
  src/utils/postLikeFn.ts
Labels: ✨ Feat, 🎨 Design

#237 [FIX] 유저모달창 검색 및 렌더링 시 로딩창 추가
  src/components/ImageCard.tsx
  src/components/userlistModal/UserListModal.tsx
  src/types/UserProfile.d.ts
Labels: 🔧 Fix

#241 [FEAT] 상세게시글 상단 게시판이름 클릭 시 해당 게시판으로 이동 구현
  src/components/PostDetail/PostInfo.tsx
Labels: ✨ Feat

#239 [BUG] 마이페이지 좋아요 버그 수정
  src/components/ImageCard.tsx
  src/pages/MyPage.tsx
  src/types/Post.d.ts
Labels: 🐛 Bug, 🔧 Fix

#243 [BUG] 이미지카드 긴급 수정
  src/components/ImageCard.tsx
Labels: 🐛 Bug, 🔧 Fix

#245 [FEAT] 메인페이지
  index.html
  package.json
  src/App.tsx
  src/assets/images/banner.png
  src/components/main/BmiCon.tsx
  src/components/main/SwiperCustom.tsx
  src/components/rootlayout/Sidebar.tsx
  src/css/index.css
  src/css/swiper.css
  src/pages/Main.tsx
Labels: ✨ Feat

#246 [Fix] 유저정보 변경로직수정
  src/components/FollowButton.tsx
  src/components/User/UserCard.tsx
  src/components/UserProfile.tsx
Labels: 🔧 Fix

#251 Feat 유저페이지 #211
  src/components/User/UserInfoCard.tsx
  src/pages/User.tsx
  src/types/UserInfo.d.ts
Labels: ✨ Feat

#253 [FEAT] 메인 bmi 계산기 기능 구현
  src/components/main/BmiCon.tsx
Labels: ✨ Feat

#255 [FEAT] 다크모드 임시 구현
  src/components/button/ModeChange.tsx
  src/components/userlistModal/UserListModal.tsx
  src/stores/darkModeStore.ts
  tailwind.config.js
Labels: ✨ Feat

#257 [FEAT] 무한스크롤 구현
  src/components/ImageCard.tsx
  src/components/InfinityLoading.tsx
  src/main.tsx
  src/pages/Home.tsx
Labels: ✨ Feat

#262 [FEAT] 게시물 수정시 로딩화면 추가
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
Labels: ✨ Feat

#263 Bug 게시물날짜 #258
  src/components/Review.tsx
  src/pages/MyPage.tsx
  src/pages/ReviewPost.tsx
  src/pages/User.tsx
Labels: 🐛 Bug

#269 Feat 유저프로필 클릭 이동 #267
  src/components/ImageCard.tsx
  src/components/PostDetail/PostInfo.tsx
  src/components/Review.tsx
  src/pages/PostDetail.tsx
Labels: ✨ Feat

#266 [FIX] 로그인페이지 비회원으로 둘러보기 navigate수정
  src/api/axios.ts
  src/components/rootlayout/Header.tsx
  src/pages/Login.tsx
  src/stores/tokenStore.ts
Labels: 🔧 Fix

#273 [FIX] 로그인 페이지 모달 추가
  src/components/PostDetail/PostInfo.tsx
  src/components/button/ModeChange.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DeleteConfirm.tsx
  src/pages/Login.tsx
Labels: ✨ Feat, 🔧 Fix

#278 [FEAT] 댓글 삭제 / 게시물 수정 모달 구현
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/PostInfo.tsx
  src/pages/Home.tsx
  src/pages/PostDetail.tsx
Labels: ✨ Feat

#281 [FIX] 댓글 날짜 형식 수정
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/PostInfo.tsx
Labels: 🔧 Fix

#282 [FEAT] 유저모달창 다크모드 구현
  src/assets/darkicons/darkClose.svg
  src/assets/darkicons/darkLeftIcon.svg
  src/assets/darkicons/darkRightIcon.svg
  src/assets/darkicons/darkSearchIcon.svg
  src/components/ChannelList.tsx
  src/components/FollowButton.tsx
  src/components/rootlayout/Sidebar.tsx
  src/components/userlistModal/UserBox.tsx
  src/components/userlistModal/UserListModal.tsx
  src/components/userlistModal/UserNone.tsx
  src/css/tailwind.css
  src/pages/Login.tsx
Labels: ✨ Feat, 🎨 Design

#283 feat: 다크모드 색상값 추가
  tailwind.config.js
Labels: ✨ Feat

#287 [FEAT]277_Notification_Count
  src/components/notification/Notification.tsx
  src/utils/commentFn.ts
Labels: ✨ Feat

#288 [FIX] 마이페이지 호버 오류 수정
  src/components/MyImageCard.tsx
  src/pages/MyPage.tsx
  src/types/MyImageCard.d.ts
Labels: 🐛 Bug, 🔧 Fix

#290 [DESIGN] 마이페이지 / 유저 페이지의 하단 padding 값 추가
  src/pages/MyPage.tsx
  src/pages/User.tsx
Labels: 🎨 Design

#291 feat: 헤더 다크모드
  src/assets/darkicons/darkNotifyIcon.svg
  src/assets/horizontalNight.svg
  src/components/button/ModeChange.tsx
  src/components/rootlayout/Header.tsx
Labels: ✨ Feat

#297 [FIX] 게시물 삭제 시 해당채널로 이동
  src/components/PostDetail/PostInfo.tsx
Labels: 🔧 Fix

#296 [FEAT] 메인페이지 필터링 된 데이터 불러오기 #276
  src/pages/Main.tsx
Labels: ✨ Feat

#300 feat: 회원가입 다크모드
  src/assets/darkicons/darkShowPwImg.svg
  src/pages/Signup.tsx
Labels: ✨ Feat

#299 Feat 로그인페이지 다크모드 #280
  src/assets/darkicons/darkAuthBgImg.svg
  src/layouts/AuthLayout.tsx
  src/pages/Login.tsx
Labels: ✨ Feat

#301 [FIX] 유저페이지 타입오류수정
  src/components/ImageCard.tsx
  src/pages/User.tsx
  src/types/Post.d.ts
Labels: 🔧 Fix

#304 [BUG] : 댓글 없을 때 전송시 생기는 오류 수정
  src/components/ButtonComponent.tsx
  src/components/PostDetail/CommentForm.tsx
  src/types/ButtonComponent.d.ts
Labels: 🐛 Bug, 🎨 Design

#306 feat: 로그인모달창 다크모드 구현
  src/components/modal/ConfirmModal.tsx
  src/pages/Login.tsx
Labels: ✨ Feat

#305 [FIX] 게시글 수정시 채널 링크 이동 막기, 디자인 수정
  src/components/PostDetail/PostInfo.tsx
Labels: 🔧 Fix, 🎨 Design

#310 [BUG]307_Notification_myself_ban
  src/components/notification/Notification.tsx
  src/utils/commentFn.ts
  src/utils/postLikeFn.ts
Labels: 🐛 Bug, 🔧 Fix

#312 [FEAT] 채널페이지 다크모드 구현
  src/components/ImageCard.tsx
  src/components/SearchBar.tsx
  src/pages/Home.tsx
Labels: ✨ Feat

#313 [FEAT] 메인 페이지 로딩창 추가
  src/pages/Main.tsx
Labels: ✨ Feat

#314 fix: 회원가입로그인 다크모드
  src/assets/lightAuthBgImg.svg
  src/components/ButtonComponent.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/rootlayout/Header.tsx
  src/layouts/AuthLayout.tsx
  src/pages/Login.tsx
  src/types/ButtonComponent.d.ts
Labels: 🔧 Fix

#318 [FIX] 헬스장 리뷰 컴포넌트 / 페이지 수정
  src/components/Review.tsx
  src/pages/Home.tsx
  src/pages/ReviewPost.tsx
Labels: 🔧 Fix, 🎨 Design

#319 Feat error페이지다크모드 #316
  src/components/rootlayout/Header.tsx
  src/components/rootlayout/Sidebar.tsx
  src/layouts/AuthLayout.tsx
  src/pages/Error.tsx
Labels: ✨ Feat, 🔧 Fix

#317 feat:유저페이지 다크모드 구현
  src/components/ImageCard.tsx
  src/components/User/UserInfoCard.tsx
  src/components/modal/ConfirmModal.tsx
  src/pages/Login.tsx
  src/pages/User.tsx
Labels: ✨ Feat

#322 [FIX] 버튼 컴포넌트 수정
  src/components/ButtonComponent.tsx
Labels: 🔧 Fix, 🎨 Design

#326 fix: 다크모드 유저목록 아이콘 추가 및 보더색 변경경
  src/assets/darkicons/darkUserListIcon.svg
  src/components/rootlayout/Sidebar.tsx
Labels: 🔧 Fix

#329 [FEAT]328_NotificationRefresh_design_imageLink
  src/components/NotificationBox.tsx
  src/components/notification/Notification.tsx
  src/components/rootlayout/Header.tsx
Labels: ✨ Feat, 🔧 Fix, 🎨 Design

#336 [design]Notification_Redesign
  src/components/NotificationBox.tsx
  src/components/notification/Notification.tsx
Labels: 🎨 Design

#344 [FEAT] 상세 게시글 다크모드 구현
  src/assets/darkicons/darkCommentIcon.svg
  src/assets/darkicons/darkPostLeft.svg
  src/assets/darkicons/darkPostRight.svg
  src/components/PostDetail/CommentBox.tsx
  src/components/PostDetail/CommentForm.tsx
  src/components/PostDetail/CommentSec.tsx
  src/components/PostDetail/PostInfo.tsx
  src/pages/PostDetail.tsx
Labels: ✨ Feat, 🎨 Design

#342 Feat 마이페이지 다크모드 구현
  src/assets/darkicons/darkProfileEdit.svg
  src/components/MyImageCard.tsx
  src/components/MyPage/CustomCalendar.tsx
  src/components/User/UserCard.tsx
  src/components/UserProfile.tsx
  src/css/calendar.css
  src/pages/MyPage.tsx
  src/pages/User.tsx
Labels: ✨ Feat

#346 [FIX] post 리스트 미디어쿼리 적용
  src/components/ImageCard.tsx
  src/components/records/PostList.tsx
  src/pages/Home.tsx
  src/utils/api/deletePosts.ts
  src/utils/api/getChannelPost.ts
Labels: 🔧 Fix, 🎨 Design

#349 Feat 게시글 작성 페이지 다크모드
  src/assets/darkicons/darkDown.svg
  src/assets/darkicons/darkSelectChannel.svg
  src/assets/darkicons/darkUploadImgIcon.svg
  src/assets/darkicons/darkWriteTitle.svg
  src/components/posting/PostStatus.tsx
  src/pages/Posting.tsx
Labels: ✨ Feat

#351 [FEAT] 메인페이지 다크모드 구현
  src/components/main/BmiCon.tsx
  src/components/main/SwiperCustom.tsx
  src/css/swiper.css
  src/pages/Main.tsx
Labels: ✨ Feat, 🎨 Design

#352 [FEAT] 사이드바 닫은 상태에서 새로고침하면 자동 열림 수정
  src/stores/sideberToggleStore.ts
Labels: 🔧 Fix

#355 [DESIGN] 로그인 / 회원가입 반응형 추가
  src/components/rootlayout/Header.tsx
  src/layouts/AuthLayout.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: 🔧 Fix, 🎨 Design

#335 feat: 다크모드 알림창
  src/assets/darkicons/darkCommentIcon.svg
  src/assets/darkicons/darkFollowIcon.svg
  src/assets/darkicons/darkLikeIcon.svg
  src/assets/noti_follow_Icon.svg
  src/components/NotificationBox.tsx
  src/components/notification/Notification.tsx
Labels: ✨ Feat

#358 fix: 헤더 보더 삭제
  src/components/rootlayout/Header.tsx
Labels: 🔧 Fix

#361 [DESIGN] 버튼 비활성화시 호버 애니메이션 제거
  src/pages/PostDetail.tsx
Labels: 🎨 Design

#365 feat: checkdone 다크모드 색 추가
  src/components/checkDone/DoneProgressBar.tsx
Labels: ✨ Feat

#367 fix: 캘린더 원색깔 변경
  src/css/calendar.css
Labels: 🔧 Fix

#368 Feat 헬스장리뷰페이지 다크모드
  src/components/Review.tsx
  src/pages/ReviewPost.tsx
Labels: ✨ Feat, 🎨 Design
